package by.urbel.hotel.controller.command;

public enum CommandName {
    AUTHORIZE,
    REGISTER,
    LOGOUT,
    FIND_FREE_CATEGORIES_BY_BEDS_NUMBER,
    FIND_ALL_ROOMS,
    FIND_ALL_CATEGORIES,
    FIND_ALL_RESERVATIONS,
    GO_TO_ADD_ROOM_PAGE,
    ADD_NEW_ROOM,
    ADD_NEW_CATEGORY,
    DELETE_ROOM,
    DELETE_CATEGORY,
    BLOCK_ROOM,
    UNBLOCK_ROOM,
    RESERVE_ROOM,
    GO_TO_PROFILE_PAGE,
    DELETE_RESERVATION,
    UPDATE_USER
}
